### ISSUE TITLE
is longtail detection methods work on V3det

### ISSUE THREAD

**Issue by twangnh** [V3Det/V3Det#10]
Hi @V3Det @panzhang0212 thanks for realeasing V3Det, we are wondering if it is evaluated on the long-tailed distribution object detection methods, e.g., eqlv2, seesaw loss, groupsoftmax, ...

**Comment by V3Det** [comment]
Based on our experience, long-tailed methods such as eqlv2, seesaw loss, and groupsoftmax will not lead to significant improvements on V3Det, due to V3Det's class distribution is not very long-tailed.
