### ISSUE TITLE
Why it looks contradictory in category_tree.json

### ISSUE THREAD

**Issue by seanzhuh** [V3Det/V3Det#15]
Hi,
    Thanks for your great work.
    Regarding v3det_2023_v1_category_tree.json, I'm confused about it.
    Specifically, why 
    `len(tree['ancestor2descendant']['n00001740']) + 1` (14545) does not equal to `len(tree['id2name'])` (18260), neither of them equals to `child_num['n00001740']` (26830) in function `def init_tree` in `v3det_visualize_tree.py`. 
    From my understanding, all these three numbers represent the number of nodes in the tree.

**Comment by V3Det** [comment]
The item `ancestor2descendant` refers to all non-repeating descendants of a node. The length of them is the number inside the parentheses behind the first-row node in the lower-left view of the visualization UI. The item `child_num` includes descendants that may appear repeatedly under the given ancestor node. For example, the fish belongs to both vertebrates and seafood. Therefore, in the node of animals, the fish will be counted multiple times due to its multiple classification. The item "child_num" is the number inside the parentheses behind the node in the upper-left view of the visualization UI. It's important to note that not all nodes in "id2name" are present in the category tree, such as the categories cannot be used for detection.

**Comment by seanzhuh** [comment]
So the total unique nodes are 14545 which is the `len(tree['ancestor2descendant']['n00001740']) + 1` right ?

And for the visualization UI, It throws an error on mac os, below is the stack trace, what could be the problem?

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSApplication macOSVersion]: unrecognized selector sent to instance 0x12a6bbe40'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000185c98570 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000185789eb4 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000185d4a12c -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x0000000185c027d4 ___forwarding___ + 1572
	4   CoreFoundation                      0x0000000185c020f0 _CF_forwarding_prep_0 + 96
	5   libtk8.6.dylib                      0x0000000101617b14 GetRGBA + 48
	6   libtk8.6.dylib                      0x0000000101617600 SetCGColorComponents + 144
	7   libtk8.6.dylib                      0x0000000101617974 TkpGetColor + 344
	8   libtk8.6.dylib                      0x0000000101578d40 Tk_GetColor + 220
	9   libtk8.6.dylib                      0x000000010156c480 Tk_Get3DBorder + 204
	10  libtk8.6.dylib                      0x000000010156c2b0 Tk_Alloc3DBorderFromObj + 144
	11  libtk8.6.dylib                      0x000000010157a0cc DoObjConfig + 832
	12  libtk8.6.dylib                      0x0000000101579c88 Tk_InitOptions + 348
	13  libtk8.6.dylib                      0x0000000101579b84 Tk_InitOptions + 88
	14  libtk8.6.dylib                      0x00000001015a1b10 CreateFrame + 1440
	15  libtk8.6.dylib                      0x00000001015a1e08 TkListCreateFrame + 156
	16  libtk8.6.dylib                      0x000000010159adb8 Initialize + 1840
	17  _tkinter.cpython-311-darwin.so      0x000000010126634c Tcl_AppInit + 80
	18  _tkinter.cpython-311-darwin.so      0x00000001012608a4 Tkapp_New + 592
	19  _tkinter.cpython-311-darwin.so      0x000000010126028c _tkinter_create + 608
	20  libpython3.11.dylib                 0x00000001018d488c cfunction_vectorcall_FASTCALL + 260
	21  libpython3.11.dylib                 0x000000010188a320 PyObject_Vectorcall + 80
	22  libpython3.11.dylib                 0x000000010196a668 _PyEval_EvalFrameDefault + 35160
	23  libpython3.11.dylib                 0x0000000101961c70 _PyEval_Vector + 200
	24  libpython3.11.dylib                 0x0000000101889c9c _PyObject_FastCallDictTstate + 272
	25  libpython3.11.dylib                 0x000000010188a9ec _PyObject_Call_Prepend + 160
	26  libpython3.11.dylib                 0x00000001018f721c slot_tp_init + 188
	27  libpython3.11.dylib                 0x00000001018ecd18 type_call + 424
	28  libpython3.11.dylib                 0x0000000101889e84 _PyObject_MakeTpCall + 344
	29  libpython3.11.dylib                 0x000000010196a668 _PyEval_EvalFrameDefault + 35160
	30  libpython3.11.dylib                 0x0000000101961c70 _PyEval_Vector + 200
	31  libpython3.11.dylib                 0x0000000101889c9c _PyObject_FastCallDictTstate + 272
	32  libpython3.11.dylib                 0x000000010188a9ec _PyObject_Call_Prepend + 160
	33  libpython3.11.dylib                 0x00000001018f721c slot_tp_init + 188
	34  libpython3.11.dylib                 0x00000001018ecd18 type_call + 424
	35  libpython3.11.dylib                 0x0000000101889e84 _PyObject_MakeTpCall + 344
	36  libpython3.11.dylib                 0x000000010196a668 _PyEval_EvalFrameDefault + 35160
	37  libpython3.11.dylib                 0x0000000101961b40 PyEval_EvalCode + 272
	38  libpython3.11.dylib                 0x00000001019b4a98 run_mod + 152
	39  libpython3.11.dylib                 0x00000001019b2f8c _PyRun_SimpleFileObject + 852
	40  libpython3.11.dylib                 0x00000001019b2a14 _PyRun_AnyFileObject + 160
	41  libpython3.11.dylib                 0x00000001019d1e70 Py_RunMain + 1848
	42  libpython3.11.dylib                 0x00000001019d2220 pymain_main + 324
	43  libpython3.11.dylib                 0x00000001019d22c0 Py_BytesMain + 40
	44  dyld                                0x00000001857c50e0 start + 2360
)
libc++abi: terminating due to uncaught exception of type NSException
zsh: abort      python v3det_visualize_tree.py
