### ISSUE TITLE
One image url is failed. Could you please fix the failed URL?

### ISSUE THREAD

**Issue by launchauto** [V3Det/V3Det#2]
Thanks for your outstanding work.
I download successfully 213,174 images, but one failed. 
The failed image name is : 
images/a00001618/13_2334_7020112209_c24fb4dd54_c.jpg
and the according URL is:
https://live.staticflickr.com/7069/7020112209_c24fb4dd54_c.jpg
When you click on this website, it will remind you that "These aren't the droids you're looking for."
Could you please fix the failed URL?

**Comment by V3Det** [comment]
Thank you for reporting failed image URL. We will update it soon.

**Comment by V3Det** [comment]
> Thanks for your outstanding work. I download successfully 213,174 images, but one failed. The failed image name is : images/a00001618/13_2334_7020112209_c24fb4dd54_c.jpg and the according URL is: https://live.staticflickr.com/7069/7020112209_c24fb4dd54_c.jpg When you click on this website, it will remind you that "These aren't the droids you're looking for." Could you please fix the failed URL?

The failed URLs are updated. Please run the download script again.

**Comment by launchauto** [comment]
> > Thanks for your outstanding work. I download successfully 213,174 images, but one failed. The failed image name is : images/a00001618/13_2334_7020112209_c24fb4dd54_c.jpg and the according URL is: https://live.staticflickr.com/7069/7020112209_c24fb4dd54_c.jpg When you click on this website, it will remind you that "These aren't the droids you're looking for." Could you please fix the failed URL?
> 
> The failed URLs are updated. Please run the download script again.

Yeah, it works.
