### ISSUE TITLE
36 expired urls

### ISSUE THREAD

**Issue by Jiahao000** [V3Det/V3Det#24]
Hi @myownskyW7 @V3Det,

I tried to download the dataset but got 36 expired images. Here is the list:

[
    "images/n11876634/4_2110_8387380173_1bfeb72006_c.jpg",
    "images/n07866723/13_1450_3218478576_83918947dd_c.jpg",
    "images/Q8054336/10_1491_16930369048_f0e9512cce_c.jpg",
    "images/n03191286/26_86_43974900070_19779e833c_c.jpg",
    "images/n04529108/3_54_50535759207_8a3dfbec8f_c.jpg",
    "images/n13141415/2_2526_48702807462_d23c55395a_c.jpg",
    "images/n03012499/3_160_36327465152_06ce113d35_c.jpg",
    "images/n03162818/31_181_38467659792_9788e27e8a_c.jpg",
    "images/a00013164/5_240_24149062111_994a9b3903_c.jpg",
    "images/n15086247/20_226_35608299145_3e3e1e02d7_c.jpg",
    "images/a00007441/3_524_50568970046_99eccbd81e_c.jpg",
    "images/a00007012/29_194_21652586156_758bd1018f_c.jpg",
    "images/n07877675/22_1098_49296458528_3b9acd27b0_c.jpg",
    "images/n03191286/33_69_45067351484_28799e1eb5_c.jpg",
    "images/Q829304/6_2275_6737230971_e4bd3d5d1a_c.jpg",
    "images/n03308481/32_121_50300649508_d6285e6108_c.jpg",
    "images/n03484931/15_1123_48688985131_5c21240618_c.jpg",
    "images/n07673397/2_408_50206367377_a56f6a1f0d_c.jpg",
    "images/n02946348/22_1497_40436127113_e719d493ee_c.jpg",
    "images/a00004221/20_1305_39950924533_e5e2272692_c.jpg",
    "images/n15086247/5_681_35109117662_6618423d9a_c.jpg",
    "images/Q2757253/31_461_50892959812_77dd9df3b3_c.jpg",
    "images/n04597913/22_1286_48814230427_a0ef7af275_c.jpg",
    "images/n15086247/12_375_34025901083_30240cc46e_c.jpg",
    "images/a00008102/33_146_28872748060_c4d17e335c_c.jpg",
    "images/n04596742/14_2165_24947012484_10a6796a35_c.jpg",
    "images/n04597913/8_1782_49556385442_e6cbb75384_c.jpg",
    "images/Q2757253/21_571_50920818141_4d1a424a9e_c.jpg",
    "images/a00003178/10_179_31883273802_2725643e60_c.jpg",
    "images/n02409508/0_2664_21578475849_7d010c7170_c.jpg",
    "images/Q270997/14_271_50822619968_1b9c20858e_c.jpg",
    "images/n04015908/14_431_7609261068_576baf4294_c.jpg",
    "images/n13141415/28_1098_48841104697_807f5ce75e_c.jpg",
    "images/n03941684/16_21_50892128368_54bdd3b51c_c.jpg",
    "images/n03376595/28_2544_51294324286_1d922dca90_c.jpg",
    "images/n10247358/20_234_6220889758_cdf0c0f0d0_c.jpg"
 ]

Could you please help fix it? Thanks in advance!

**Comment by V3Det** [comment]
@Jiahao000 Please rerun the script `v3det_image_download.py` to download the missing images.

**Comment by Jiahao000** [comment]
I reran the script and got 5 expired images this time:

[
    "images/Q8054336/10_1491_16930369048_f0e9512cce_c.jpg",
    "images/n03191286/26_86_43974900070_19779e833c_c.jpg",
    "images/n04597913/8_1782_49556385442_e6cbb75384_c.jpg",
    "images/n15086247/20_226_35608299145_3e3e1e02d7_c.jpg",
    "images/a00007441/3_524_50568970046_99eccbd81e_c.jpg"
]

**Comment by V3Det** [comment]
@Jiahao000 It's OK now. Please rerun the script.
