### ISSUE TITLE
2 urls failed due to url expiration.  

### ISSUE THREAD

**Issue by jyydlut** [V3Det/V3Det#29]
"expired": [
    "images/a00013865/8_213_34733526783_3355cac7f6_c.jpg",
    "images/n12366675/27_2254_2753297186_0b0ce233df_c.jpg"
  ]
please check the expired urls, I have reran the script many times!

**Comment by V3Det** [comment]
@jyydlut The expired URLs have been updated. Please rerun the script `v3det_image_download.py` to download the missing images.
