### ISSUE TITLE
Incorrect category id mapping to treeid

### ISSUE THREAD

**Issue by launchauto** [V3Det/V3Det#3]
I find that you provide this file "v3det_2023_v1_category_tree.json" on the website.
But the "categoryid2treeid" part may be incorrect.
For example,  category['categoryid2treeid']['13026']='n07642933'
In train json, category id 13026 means Pitador( a dog crossbreed), 'n07642933' means 'jam', which is not comptiable.
The wrong mapping pairs are almost 1.2w.

**Comment by V3Det** [comment]
Please download the latest annotation files from https://[v3det.openxlab.org.cn/download](https://v3det.openxlab.org.cn/download), as we have made some modifications to the them when releasing the category tree.
