### ISSUE TITLE
what's the true meaning of id in category_tree from file "v3det_2023_v1_category_tree.json"?

### ISSUE THREAD

**Issue by UcanSee** [V3Det/V3Det#4]
Thanks for your great work! 
About this dataset I have some questions to ask:
1. I found there are many id can not be mapped to wordnet, for example,  'a00000157'. These id have same style as wordnet , Are they related to wordnet?
2.  what's ther meaning of  id2synonym_list, do ids belonging to the same list mean the same thing? For example,  as for id "a00002718", we can find three synonym: Q232755, a00002718, n07751280, so can I assume that these three ids mean the same thing?
best regards!

**Comment by V3Det** [comment]
The ```tree_id``` in the category tree does not have a one-to-one correspondence with WordNet. It includes some vocabulary from ImageNet (e.g., ```nxxxx```), as well as from other public datasets (e.g., ```axxxx``` or ```Qxxxx```), along with our supplementary vocabulary (e.g., ```xxxxx```).
The ```id2synonym_list``` represents a collection of synonyms, while ```id2center_synonym``` is the representative word for words in synonyms. You can get the specific meaning of each ```tree_id``` with ```id2name``` and ```id2desc```.
