### ISSUE TITLE
OOM when evaluating V3Det with MMDet framework.

### ISSUE THREAD

**Issue by synsin0** [V3Det/V3Det#5]
My test platform has RAM of 400GB，but it still confronted out of memory during the last stage of V3Det evaluation (after module inference, and after 197295736/197295736), may you provide some instructions on why it happens and how to avoid. Thanks.

**Comment by yhcao6** [comment]
We use multi-process in the evaluation program, which may consume much RAM resources. You may decrease the number of predefined processes [here](https://github.com/V3Det/mmdetection-V3Det/blob/eb8c521098253a1f90c628341511f041451a98c6/mmdet/datasets/api_wrappers/cocoeval_mp.py#L92) and try again
