### ISSUE TITLE
Missing Images 

### ISSUE THREAD

**Issue by lxtGH** [V3Det/V3Det#6]
Hi! It is an interesting work. We want to try it out. However, I met the download issues.  

<img width="1038" alt="image" src="https://github.com/V3Det/V3Det/assets/17202268/f83d9ccf-9ae1-49f5-a5b5-e66d8e4e0a29">

It seems 26 images are expired.

**Comment by V3Det** [comment]
We have checked and updated the URLs of these images. Please run the script ```v3det_image_download.py``` again to download them.
